spring:
  application:
    name: COMMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/commentdb
    username: root
    password: Shivendra@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka




#
#      management:
#        endpoints:
#          web:
#            exposure:
#              include: health
#        endpoint:
#          health:
#            show-details: always
#        enabled: true
#
#      resilience4j:
#        circuitbreaker:
#          instances:
#            commentBreaker:
#              registerHealthIndicator: true
#              eventConsumerBufferSize: 10
#              failureRateThreshold: 50
#              minimumNumberOfCalls: 5
#              automaticTransitionFromOpenToHalfOpenEnabled: true
#              waitDurationInOpenState: 6s
#              permittedNumberOfCallsInHalfOpenState: 3
#              slidingWindowSize: 10
#              slidingWindowType: COUNT_BASED

